#!/usr/bin/expect -f
#  ./ wl_pssphrs_autofill passphrase keyfile

set passphrase [lrange $argv 0 0]
set key_file [lrange $argv 1 1]

spawn ssh-add $key_file
expect "*passphrase*"
send -- "$passphrase\r"
interact
