#!/usr/bin/expect -f
#  ./ awl_kazan_push_autofill awl_username awl_password

set awl_username [lrange $argv 0 0]
set awl_password [lrange $argv 1 1]

spawn git push
expect "Username*"
send -- "$awl_username\r"
expect "Password*"
send -- "$awl_password\r"
interact
