#!/usr/bin/expect -f
#  ./ awl_kazan_push_autofill awl_username awl_password

set awl_password [lrange $argv 0 1]
set awl_command  [lrange $argv 1 end]

spawn sh -c "$awl_command"

expect "*assword*"
send -- "$awl_password\r"

interact

