#!/usr/bin/expect -f
#  ./ssh.exp password 192.168.1.11 id

set passphrase [lrange $argv 0 0]
set key_file [lrange $argv 1 1]

spawn ssh-add $key_file
expect "*passphrase*"
send -- "$passphrase\r"
interact
